
package Vista_Sistema_Simulacion;
import javax.swing.JOptionPane;
import javax.swing.JFileChooser;
import proyecto2.manejomemoria.*;

public class Vista_Seleccion_Archivos extends javax.swing.JInternalFrame {

     String Archivo_Referencias;
    String Archivo_Procesos;
    proyecto2.manejomemoria.DTO Informacion_DTO;
    
    public Vista_Seleccion_Archivos(proyecto2.manejomemoria.DTO Informacion_DTO) {
        initComponents();
        this.Informacion_DTO= Informacion_DTO;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Descripción_Programa = new javax.swing.JLabel();
        Indicaciones1 = new javax.swing.JLabel();
        Indicaciones2 = new javax.swing.JLabel();
        Indicaciones3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Boton_Seleccionar_Archivo_Proceso = new javax.swing.JButton();
        Boton_Seleccionar_Archivo_Referencias = new javax.swing.JButton();
        Boton_Regresar = new javax.swing.JButton();
        Boton_Agregar_Archivos = new javax.swing.JButton();

        setClosable(true);
        setTitle("Seleccionar archivos");

        Descripción_Programa.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Descripción_Programa.setText("Programa de simulación de gestión de memoria.");

        Indicaciones1.setText("Para el funcionamiento del sistema de simulación se requiere que seleccione dos archivos con extensión .txt:");

        Indicaciones2.setText("El archivo contiene la información de los procesos.");

        Indicaciones3.setText("El archivo contiene la información de las referencias.");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Seleccionar Archivo de Procesos");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Seleccionar Archivo de Referencias");

        Boton_Seleccionar_Archivo_Proceso.setText("Examinar");
        Boton_Seleccionar_Archivo_Proceso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_Seleccionar_Archivo_ProcesoActionPerformed(evt);
            }
        });

        Boton_Seleccionar_Archivo_Referencias.setText("Examinar");
        Boton_Seleccionar_Archivo_Referencias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_Seleccionar_Archivo_ReferenciasActionPerformed(evt);
            }
        });

        Boton_Regresar.setText("Regresar");

        Boton_Agregar_Archivos.setText("Agregar Archivos al Sistema");
        Boton_Agregar_Archivos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_Agregar_ArchivosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Descripción_Programa, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addComponent(Indicaciones1)
                .addContainerGap(164, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(160, 160, 160)
                            .addComponent(Boton_Agregar_Archivos)
                            .addGap(55, 55, 55)
                            .addComponent(Boton_Regresar, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(Indicaciones2)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(Boton_Seleccionar_Archivo_Proceso)))
                            .addGap(215, 215, 215)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addGap(18, 18, 18)
                                    .addComponent(Boton_Seleccionar_Archivo_Referencias))
                                .addComponent(Indicaciones3))))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Descripción_Programa)
                .addGap(35, 35, 35)
                .addComponent(Indicaciones1)
                .addGap(0, 350, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(123, 123, 123)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(Boton_Seleccionar_Archivo_Proceso)
                        .addComponent(jLabel2)
                        .addComponent(Boton_Seleccionar_Archivo_Referencias))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Indicaciones2)
                        .addComponent(Indicaciones3))
                    .addGap(96, 96, 96)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Boton_Regresar)
                        .addComponent(Boton_Agregar_Archivos))
                    .addContainerGap(124, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Boton_Seleccionar_Archivo_ProcesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_Seleccionar_Archivo_ProcesoActionPerformed
        JFileChooser Elegir_Archivo= new JFileChooser();
        int resultado= Elegir_Archivo.showOpenDialog(null);
        if (resultado== JFileChooser.APPROVE_OPTION){
            Archivo_Procesos = Elegir_Archivo.getSelectedFile().getAbsolutePath();
            

        }
    }//GEN-LAST:event_Boton_Seleccionar_Archivo_ProcesoActionPerformed

    private void Boton_Seleccionar_Archivo_ReferenciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_Seleccionar_Archivo_ReferenciasActionPerformed
        JFileChooser Elegir_Archivo= new JFileChooser();
        int resultado= Elegir_Archivo.showOpenDialog(null);
        if (resultado== JFileChooser.APPROVE_OPTION){
            Archivo_Referencias = Elegir_Archivo.getSelectedFile().getAbsolutePath();
            
        }
    }//GEN-LAST:event_Boton_Seleccionar_Archivo_ReferenciasActionPerformed

    private void Boton_Agregar_ArchivosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_Agregar_ArchivosActionPerformed
        if ((Archivo_Referencias==null)&&(Archivo_Procesos==null)) {
            JOptionPane.showMessageDialog(null,"No ha seleccionado los archivos",null,JOptionPane.ERROR_MESSAGE);
        }
        else if (Archivo_Referencias==null) {
            JOptionPane.showMessageDialog(null,"No ha seleccionado el archivo de referencias",null,JOptionPane.ERROR_MESSAGE);
        }
        else if (Archivo_Procesos==null) {
            JOptionPane.showMessageDialog(null,"No ha seleccionado el archivo de procesos",null,JOptionPane.ERROR_MESSAGE);
        }
        else{
          
          Informacion_DTO.Agregar_Archivos(Archivo_Procesos, Archivo_Referencias);
          JOptionPane.showMessageDialog(null,"Archivos agregados correctamente al sistema",null,JOptionPane.INFORMATION_MESSAGE);
          //Mostrar Pantalla del sistema
        }
    }//GEN-LAST:event_Boton_Agregar_ArchivosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Boton_Agregar_Archivos;
    private javax.swing.JButton Boton_Regresar;
    private javax.swing.JButton Boton_Seleccionar_Archivo_Proceso;
    private javax.swing.JButton Boton_Seleccionar_Archivo_Referencias;
    private javax.swing.JLabel Descripción_Programa;
    private javax.swing.JLabel Indicaciones1;
    private javax.swing.JLabel Indicaciones2;
    private javax.swing.JLabel Indicaciones3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
