
package Vista_Sistema_Simulacion;
import proyecto2.manejomemoria.*;
import java.util.*;
import javax.swing.JButton;


public class Vista_Memoria_Fisica extends javax.swing.JInternalFrame {

    private List<JButton> listaBotones = new ArrayList<>();
   private LinkedList <proyecto2.manejomemoria.Marco>Marcos;
    public Vista_Memoria_Fisica(LinkedList <proyecto2.manejomemoria.Marco>Marcos) {
        initComponents();
        this.Marcos=Marcos;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Indicaciones = new javax.swing.JLabel();
        Cantidad_Referencias = new javax.swing.JLabel();
        Referencias = new javax.swing.JLabel();

        setClosable(true);
        setTitle("Visualizar Memoria Física");

        Indicaciones.setText("La tabla muestra como está compuesta la memoria física despúes de");

        Cantidad_Referencias.setText("#");

        Referencias.setText("referencias");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Indicaciones)
                .addGap(18, 18, 18)
                .addComponent(Cantidad_Referencias)
                .addGap(18, 18, 18)
                .addComponent(Referencias)
                .addGap(0, 308, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Indicaciones)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Cantidad_Referencias)
                        .addComponent(Referencias)))
                .addContainerGap(309, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Cantidad_Referencias;
    private javax.swing.JLabel Indicaciones;
    private javax.swing.JLabel Referencias;
    // End of variables declaration//GEN-END:variables
}
