
package Vista_Sistema_Simulacion;
import proyecto2.manejomemoria.*;
import javax.swing.JOptionPane;
import javax.swing.JFileChooser;
public class Vista_Seleccion_Archivos extends javax.swing.JFrame {

    String Archivo_Referencias;
    String Archivo_Procesos;
    public Vista_Seleccion_Archivos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Descripción_Programa = new javax.swing.JLabel();
        Selección_Archivos = new javax.swing.JLabel();
        Indicaciones1 = new javax.swing.JLabel();
        Indicaciones2 = new javax.swing.JLabel();
        Indicaciones3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Boton_Seleccionar_Archivo_Proceso = new javax.swing.JButton();
        Boton_Seleccionar_Archivo_Referencias = new javax.swing.JButton();
        Boton_Regresar = new javax.swing.JButton();
        Boton_Agregar_Archivos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Descripción_Programa.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Descripción_Programa.setText("Programa de simulación de gestión de memoria.");

        Selección_Archivos.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Selección_Archivos.setText("Selección de Archivos");

        Indicaciones1.setText("Para el funcionamiento del sistema de simulación se requiere que seleccione dos archivos:");

        Indicaciones2.setText("Un archivo que contenga la información de los procesos.");

        Indicaciones3.setText("Otro archivo que contenga la información de las referencias.");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Seleccionar Archivo de Procesos");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Seleccionar Archivo de Referencias");

        Boton_Seleccionar_Archivo_Proceso.setText("Examinar");
        Boton_Seleccionar_Archivo_Proceso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_Seleccionar_Archivo_ProcesoActionPerformed(evt);
            }
        });

        Boton_Seleccionar_Archivo_Referencias.setText("Examinar");
        Boton_Seleccionar_Archivo_Referencias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_Seleccionar_Archivo_ReferenciasActionPerformed(evt);
            }
        });

        Boton_Regresar.setText("Regresar");

        Boton_Agregar_Archivos.setText("Agregar Archivos al Sistema");
        Boton_Agregar_Archivos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_Agregar_ArchivosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Descripción_Programa, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(217, 217, 217)
                        .addComponent(Boton_Agregar_Archivos)
                        .addGap(145, 145, 145)
                        .addComponent(Boton_Regresar, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Indicaciones2)
                            .addComponent(Indicaciones1)
                            .addComponent(Indicaciones3))))
                .addContainerGap(215, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(Boton_Seleccionar_Archivo_Proceso)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Boton_Seleccionar_Archivo_Referencias)
                .addGap(139, 139, 139))
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(64, 64, 64))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Selección_Archivos)
                .addGap(349, 349, 349))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Descripción_Programa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Selección_Archivos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Indicaciones1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Indicaciones2)
                .addGap(1, 1, 1)
                .addComponent(Indicaciones3)
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Boton_Seleccionar_Archivo_Proceso)
                    .addComponent(Boton_Seleccionar_Archivo_Referencias))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Boton_Regresar)
                    .addComponent(Boton_Agregar_Archivos))
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Boton_Seleccionar_Archivo_ProcesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_Seleccionar_Archivo_ProcesoActionPerformed
        JFileChooser Elegir_Archivo= new JFileChooser();
        int resultado= Elegir_Archivo.showOpenDialog(null);
        if (resultado== JFileChooser.APPROVE_OPTION){
            Archivo_Procesos = Elegir_Archivo.getSelectedFile().getAbsolutePath();
            System.out.println(Archivo_Procesos);
            
        }
    }//GEN-LAST:event_Boton_Seleccionar_Archivo_ProcesoActionPerformed

    private void Boton_Seleccionar_Archivo_ReferenciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_Seleccionar_Archivo_ReferenciasActionPerformed
         JFileChooser Elegir_Archivo= new JFileChooser();
        int resultado= Elegir_Archivo.showOpenDialog(null);
        if (resultado== JFileChooser.APPROVE_OPTION){
            Archivo_Referencias = Elegir_Archivo.getSelectedFile().getAbsolutePath();
            System.out.println(Archivo_Referencias);
        }
    }//GEN-LAST:event_Boton_Seleccionar_Archivo_ReferenciasActionPerformed

    private void Boton_Agregar_ArchivosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_Agregar_ArchivosActionPerformed
        if ((Archivo_Referencias==null)&&(Archivo_Procesos==null)) {
            JOptionPane.showMessageDialog(null,"No ha seleccionado los archivos",null,JOptionPane.ERROR_MESSAGE);
        }
        else if (Archivo_Referencias==null) {
            JOptionPane.showMessageDialog(null,"No ha seleccionado el archivo de referencias",null,JOptionPane.ERROR_MESSAGE);
        }
        else if (Archivo_Procesos==null) {
            JOptionPane.showMessageDialog(null,"No ha seleccionado el archivo de procesos",null,JOptionPane.ERROR_MESSAGE);
        }
        else{
            //tengo que pasar el dto para esta pantalla
        }
    }//GEN-LAST:event_Boton_Agregar_ArchivosActionPerformed
  
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vista_Seleccion_Archivos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vista_Seleccion_Archivos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vista_Seleccion_Archivos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vista_Seleccion_Archivos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vista_Seleccion_Archivos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Boton_Agregar_Archivos;
    private javax.swing.JButton Boton_Regresar;
    private javax.swing.JButton Boton_Seleccionar_Archivo_Proceso;
    private javax.swing.JButton Boton_Seleccionar_Archivo_Referencias;
    private javax.swing.JLabel Descripción_Programa;
    private javax.swing.JLabel Indicaciones1;
    private javax.swing.JLabel Indicaciones2;
    private javax.swing.JLabel Indicaciones3;
    private javax.swing.JLabel Selección_Archivos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
