
package Vista_Sistema_Simulacion;
import proyecto2.manejomemoria.*;

public class Vista_Configuracion_del_Sistema extends javax.swing.JFrame {

    /**
     * Creates new form Vista_Configuracion_del_Sistema
     */
    public Vista_Configuracion_del_Sistema() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Grupo_RB_Política_Recuperación = new javax.swing.ButtonGroup();
        Grupo_RB_Política_Ubicación = new javax.swing.ButtonGroup();
        Grupo_RB_Política_Reemplazo = new javax.swing.ButtonGroup();
        Grupo_RB_Tamaño_residente = new javax.swing.ButtonGroup();
        Grupo_RB_Ambito_reemplazo_residente = new javax.swing.ButtonGroup();
        Grupo_RB_Política_Limpieza = new javax.swing.ButtonGroup();
        Configuración_Sistema = new javax.swing.JLabel();
        Descripción_Programa = new javax.swing.JLabel();
        Indicaciones_Programa = new javax.swing.JLabel();
        Política_recuperación = new javax.swing.JLabel();
        RB_Bajo_Demanda = new javax.swing.JRadioButton();
        RB_Paginación_Adelantada = new javax.swing.JRadioButton();
        Política_Ubicación = new javax.swing.JLabel();
        RB_Primer_Ajuste = new javax.swing.JRadioButton();
        RB_Siguiente_Ajuste = new javax.swing.JRadioButton();
        Política_reemplazo = new javax.swing.JLabel();
        RB_Optimo = new javax.swing.JRadioButton();
        RB_LRU = new javax.swing.JRadioButton();
        RB_FIFO = new javax.swing.JRadioButton();
        RB_Reloj = new javax.swing.JRadioButton();
        Gestión_conjunto_residente = new javax.swing.JLabel();
        Tamaño_Conjunto_residente = new javax.swing.JLabel();
        RB_Fijo = new javax.swing.JRadioButton();
        RB_Variable = new javax.swing.JRadioButton();
        Ambito_reemplazo_conjunto = new javax.swing.JLabel();
        RB_Global = new javax.swing.JRadioButton();
        RB_Local = new javax.swing.JRadioButton();
        Política_Limpieza = new javax.swing.JLabel();
        RB_Bajo_Demanda_L = new javax.swing.JRadioButton();
        RB_Limpieza_adelantada = new javax.swing.JRadioButton();
        Control_carga = new javax.swing.JLabel();
        Grado_multiprogramación = new javax.swing.JLabel();
        Text_Grado_Multiprogramación = new javax.swing.JTextField();
        Indicaciones2 = new javax.swing.JLabel();
        Indicaciones_tamaño_memorias = new javax.swing.JLabel();
        Cantidad_memoria = new javax.swing.JLabel();
        Text_Tamaño_direcciones = new javax.swing.JTextField();
        bits = new javax.swing.JLabel();
        Distribucción_direcciones = new javax.swing.JLabel();
        Tamaño_pagina = new javax.swing.JLabel();
        Text_tamaño_pagina = new javax.swing.JTextField();
        Indicación3 = new javax.swing.JLabel();
        Cantidad_memoria_fisica = new javax.swing.JLabel();
        Text_Cantidad_memoria_fisica = new javax.swing.JTextField();
        KB = new javax.swing.JLabel();
        Visualizar_estado = new javax.swing.JLabel();
        Cantidad_referencias = new javax.swing.JLabel();
        Text_Cantidad_referencias = new javax.swing.JTextField();
        Botón_Crear_Sistema = new javax.swing.JButton();
        Salir = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 153, 153));
        setForeground(new java.awt.Color(0, 153, 153));

        Configuración_Sistema.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Configuración_Sistema.setText("Configuración del sistema");

        Descripción_Programa.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Descripción_Programa.setText("Programa de simulación de gestión de memoria.");

        Indicaciones_Programa.setText("Existen diferentes algoritmos para los aspectos de la gestión de la memoria ");

        Política_recuperación.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Política_recuperación.setText("Política de recuperación");

        Grupo_RB_Política_Recuperación.add(RB_Bajo_Demanda);
        RB_Bajo_Demanda.setText("Bajo Demanda");

        Grupo_RB_Política_Recuperación.add(RB_Paginación_Adelantada);
        RB_Paginación_Adelantada.setText("Paginación Adelantada");

        Política_Ubicación.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Política_Ubicación.setText("Política de ubicación");

        Grupo_RB_Política_Ubicación.add(RB_Primer_Ajuste);
        RB_Primer_Ajuste.setText("Primer Ajuste");
        RB_Primer_Ajuste.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RB_Primer_AjusteActionPerformed(evt);
            }
        });

        Grupo_RB_Política_Ubicación.add(RB_Siguiente_Ajuste);
        RB_Siguiente_Ajuste.setText("Siguiente Ajuste");
        RB_Siguiente_Ajuste.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RB_Siguiente_AjusteActionPerformed(evt);
            }
        });

        Política_reemplazo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Política_reemplazo.setText("Política de reemplazo");

        Grupo_RB_Política_Reemplazo.add(RB_Optimo);
        RB_Optimo.setText("Óptimo");

        Grupo_RB_Política_Reemplazo.add(RB_LRU);
        RB_LRU.setText("Usado menos recientemente");

        Grupo_RB_Política_Reemplazo.add(RB_FIFO);
        RB_FIFO.setText("FIFO");

        Grupo_RB_Política_Reemplazo.add(RB_Reloj);
        RB_Reloj.setText("Del reloj");

        Gestión_conjunto_residente.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Gestión_conjunto_residente.setText("Gestión del conjunto residente");

        Tamaño_Conjunto_residente.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        Tamaño_Conjunto_residente.setText("Tamaño del conjunto residente");

        Grupo_RB_Tamaño_residente.add(RB_Fijo);
        RB_Fijo.setText("Fijo");

        Grupo_RB_Tamaño_residente.add(RB_Variable);
        RB_Variable.setText("Variable");

        Ambito_reemplazo_conjunto.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        Ambito_reemplazo_conjunto.setText("Ámbito de reemplazo");

        Grupo_RB_Ambito_reemplazo_residente.add(RB_Global);
        RB_Global.setText("Global");
        RB_Global.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RB_GlobalActionPerformed(evt);
            }
        });

        Grupo_RB_Ambito_reemplazo_residente.add(RB_Local);
        RB_Local.setText("Local");

        Política_Limpieza.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Política_Limpieza.setText("Política de limpieza");

        Grupo_RB_Política_Limpieza.add(RB_Bajo_Demanda_L);
        RB_Bajo_Demanda_L.setText("Bajo demanda");

        Grupo_RB_Política_Limpieza.add(RB_Limpieza_adelantada);
        RB_Limpieza_adelantada.setText("Limpieza adelantada");

        Control_carga.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Control_carga.setText("Control de carga");

        Grado_multiprogramación.setText("Grado multiprogramación:");

        Text_Grado_Multiprogramación.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Text_Grado_MultiprogramaciónActionPerformed(evt);
            }
        });
        Text_Grado_Multiprogramación.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Text_Grado_MultiprogramaciónKeyTyped(evt);
            }
        });

        Indicaciones2.setText("Escoger un algoritmo para cada aspecto de la gestión de memoria:");

        Indicaciones_tamaño_memorias.setText("Asignación del tamaño de la memoria física y el tamaño de la memoria virtual");

        Cantidad_memoria.setText("Tamaño de direcciones:");

        Text_Tamaño_direcciones.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Text_Tamaño_direccionesKeyTyped(evt);
            }
        });

        bits.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        bits.setText("bits");

        Distribucción_direcciones.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Distribucción_direcciones.setText("Distribución en bits de las direcciones");

        Tamaño_pagina.setText("Tamaño de página:");

        Text_tamaño_pagina.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Text_tamaño_paginaKeyTyped(evt);
            }
        });

        Indicación3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Indicación3.setText("La unidad de medida que utiliza la memoria son Kilobytes (KB)");

        Cantidad_memoria_fisica.setText("Cantidad memoria física: ");

        Text_Cantidad_memoria_fisica.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Text_Cantidad_memoria_fisicaKeyTyped(evt);
            }
        });

        KB.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        KB.setText("KB");

        Visualizar_estado.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Visualizar_estado.setText("Visualizar estado memoria virtual y memoria física");

        Cantidad_referencias.setText("Cantidad de referencias para visualizar estado memoria física y virtual: ");

        Text_Cantidad_referencias.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Text_Cantidad_referenciasKeyTyped(evt);
            }
        });

        Botón_Crear_Sistema.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Botón_Crear_Sistema.setText("Crear Sistema");
        Botón_Crear_Sistema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Botón_Crear_SistemaActionPerformed(evt);
            }
        });

        Salir.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Salir.setText("Salir");
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setText("Regresar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Configuración_Sistema)
                .addGap(390, 390, 390))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Descripción_Programa, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Indicaciones_Programa)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(Indicaciones2))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Política_recuperación)
                                    .addComponent(RB_Bajo_Demanda)
                                    .addComponent(RB_Paginación_Adelantada)
                                    .addComponent(Política_Ubicación)
                                    .addComponent(RB_Primer_Ajuste)
                                    .addComponent(RB_Siguiente_Ajuste)
                                    .addComponent(Política_reemplazo)
                                    .addComponent(RB_Optimo)
                                    .addComponent(RB_FIFO)
                                    .addComponent(RB_Reloj)
                                    .addComponent(RB_LRU))
                                .addGap(52, 52, 52)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Grado_multiprogramación)
                                        .addGap(18, 18, 18)
                                        .addComponent(Text_Grado_Multiprogramación, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(Control_carga)
                                    .addComponent(RB_Limpieza_adelantada)
                                    .addComponent(RB_Bajo_Demanda_L)
                                    .addComponent(Política_Limpieza)
                                    .addComponent(Gestión_conjunto_residente)
                                    .addComponent(Tamaño_Conjunto_residente)
                                    .addComponent(RB_Fijo)
                                    .addComponent(RB_Variable)
                                    .addComponent(RB_Global)
                                    .addComponent(Ambito_reemplazo_conjunto)
                                    .addComponent(RB_Local))))
                        .addGap(178, 178, 178)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Cantidad_referencias)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Text_Cantidad_referencias))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Indicaciones_tamaño_memorias)
                                    .addComponent(Distribucción_direcciones)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(Tamaño_pagina)
                                                .addGap(46, 46, 46)
                                                .addComponent(Text_tamaño_pagina, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addComponent(Cantidad_memoria)
                                                .addGap(18, 18, 18)
                                                .addComponent(Text_Tamaño_direcciones, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(bits))
                                    .addComponent(Indicación3)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Cantidad_memoria_fisica)
                                        .addGap(33, 33, 33)
                                        .addComponent(Text_Cantidad_memoria_fisica, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(KB, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(Visualizar_estado))
                                .addGap(0, 38, Short.MAX_VALUE)))))
                .addGap(24, 24, 24))
            .addGroup(layout.createSequentialGroup()
                .addGap(289, 289, 289)
                .addComponent(Botón_Crear_Sistema)
                .addGap(61, 61, 61)
                .addComponent(Salir, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Descripción_Programa)
                .addGap(2, 2, 2)
                .addComponent(Configuración_Sistema)
                .addGap(18, 18, 18)
                .addComponent(Indicaciones_Programa, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Indicaciones2)
                    .addComponent(Indicaciones_tamaño_memorias))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(Política_Ubicación)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(RB_Primer_Ajuste)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(RB_Siguiente_Ajuste))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Política_recuperación)
                            .addComponent(Gestión_conjunto_residente)
                            .addComponent(Cantidad_memoria)
                            .addComponent(Text_Tamaño_direcciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bits))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(RB_Bajo_Demanda)
                            .addComponent(Tamaño_Conjunto_residente))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(RB_Paginación_Adelantada)
                            .addComponent(RB_Fijo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(RB_Variable)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Ambito_reemplazo_conjunto)
                            .addComponent(Indicación3))
                        .addGap(5, 5, 5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(RB_Global)
                            .addComponent(Cantidad_memoria_fisica)
                            .addComponent(Text_Cantidad_memoria_fisica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(KB))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(RB_Local))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(Distribucción_direcciones)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Tamaño_pagina, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Text_tamaño_pagina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Política_reemplazo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(RB_Optimo, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(RB_FIFO)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(RB_LRU)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(RB_Reloj, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Política_Limpieza)
                            .addComponent(Visualizar_estado))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(RB_Bajo_Demanda_L)
                            .addComponent(Cantidad_referencias)
                            .addComponent(Text_Cantidad_referencias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(RB_Limpieza_adelantada))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(Control_carga)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Grado_multiprogramación)
                            .addComponent(Text_Grado_Multiprogramación, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Botón_Crear_Sistema)
                    .addComponent(Salir)
                    .addComponent(jButton1))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RB_Siguiente_AjusteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RB_Siguiente_AjusteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RB_Siguiente_AjusteActionPerformed

    private void RB_Primer_AjusteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RB_Primer_AjusteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RB_Primer_AjusteActionPerformed

    private void RB_GlobalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RB_GlobalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RB_GlobalActionPerformed

    private void Text_Grado_MultiprogramaciónActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Text_Grado_MultiprogramaciónActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Text_Grado_MultiprogramaciónActionPerformed

    private void Text_Grado_MultiprogramaciónKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Text_Grado_MultiprogramaciónKeyTyped
        char c= evt.getKeyChar();//solo acepta numeros
        if (c<'0' || c>'9')
            evt.consume();
    }//GEN-LAST:event_Text_Grado_MultiprogramaciónKeyTyped

    private void Text_Tamaño_direccionesKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Text_Tamaño_direccionesKeyTyped
        char c= evt.getKeyChar();//solo acepta numeros
        if (c<'0' || c>'9')
            evt.consume();
    }//GEN-LAST:event_Text_Tamaño_direccionesKeyTyped

    private void Text_tamaño_paginaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Text_tamaño_paginaKeyTyped
       char c= evt.getKeyChar();//solo acepta numeros
        if (c<'0' || c>'9')
            evt.consume();
    }//GEN-LAST:event_Text_tamaño_paginaKeyTyped

    private void Text_Cantidad_memoria_fisicaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Text_Cantidad_memoria_fisicaKeyTyped
        char c= evt.getKeyChar();//solo acepta numeros
        if (c<'0' || c>'9')
            evt.consume();
    }//GEN-LAST:event_Text_Cantidad_memoria_fisicaKeyTyped

    private void Text_Cantidad_referenciasKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Text_Cantidad_referenciasKeyTyped
         char c= evt.getKeyChar();//solo acepta numeros
        if (c<'0' || c>'9')
            evt.consume();
    }//GEN-LAST:event_Text_Cantidad_referenciasKeyTyped

    private void Botón_Crear_SistemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Botón_Crear_SistemaActionPerformed
        //aquí inicializo el constructor del DTO
        String Politica_Recuperacion;
        String Politica_Ubicacion;
        String Politica_Reemplazo;
        String Politica_Limpieza;
        int Tiempo_de_Limpieza;
        String Tamaño_Conjunto;
        int Minimo_Marcos;
        int Maximo_Marcos;
        int Tamano_aumento;
        String Ambito_Reemplazo;
        int Grado_Multiprogramacion;
        int Working_Set;
        int Tamaño_Memoria_Fisica;
        int Bits;//Tamaño de las direcciones
        int Tamaño_Paginas;
        String Unidad_Medida= "KB";
        
        Tamaño_Paginas= Integer.parseInt(this.Text_tamaño_pagina.getText());
        Bits= Integer.parseInt(this.Text_Tamaño_direcciones.getText());
        
        //Validacion
        if (Tamaño_Paginas<Bits){//si esto se cumple se puede seguir con la configuracion         
        
        proyecto2.manejomemoria.DTO Configuracion_sistema= new DTO( Politica_Recuperacion,  Politica_Ubicacion, 
                 Politica_Reemplazo,  Politica_Limpieza,  Tiempo_de_Limpieza,  Tamaño_Conjunto,  Minimo_Marcos,
                         Maximo_Marcos,  Tamano_aumento,  Ambito_Reemplazo,  Grado_Multiprogramacion,  Working_Set,
                                 Tamaño_Memoria_Fisica,  Bits,  Tamaño_Paginas,  Unidad_Medida);
        }
    }//GEN-LAST:event_Botón_Crear_SistemaActionPerformed

    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vista_Configuracion_del_Sistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vista_Configuracion_del_Sistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vista_Configuracion_del_Sistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vista_Configuracion_del_Sistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vista_Configuracion_del_Sistema().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Ambito_reemplazo_conjunto;
    private javax.swing.JButton Botón_Crear_Sistema;
    private javax.swing.JLabel Cantidad_memoria;
    private javax.swing.JLabel Cantidad_memoria_fisica;
    private javax.swing.JLabel Cantidad_referencias;
    private javax.swing.JLabel Configuración_Sistema;
    private javax.swing.JLabel Control_carga;
    private javax.swing.JLabel Descripción_Programa;
    private javax.swing.JLabel Distribucción_direcciones;
    private javax.swing.JLabel Gestión_conjunto_residente;
    private javax.swing.JLabel Grado_multiprogramación;
    private javax.swing.ButtonGroup Grupo_RB_Ambito_reemplazo_residente;
    private javax.swing.ButtonGroup Grupo_RB_Política_Limpieza;
    private javax.swing.ButtonGroup Grupo_RB_Política_Recuperación;
    private javax.swing.ButtonGroup Grupo_RB_Política_Reemplazo;
    private javax.swing.ButtonGroup Grupo_RB_Política_Ubicación;
    private javax.swing.ButtonGroup Grupo_RB_Tamaño_residente;
    private javax.swing.JLabel Indicaciones2;
    private javax.swing.JLabel Indicaciones_Programa;
    private javax.swing.JLabel Indicaciones_tamaño_memorias;
    private javax.swing.JLabel Indicación3;
    private javax.swing.JLabel KB;
    private javax.swing.JLabel Política_Limpieza;
    private javax.swing.JLabel Política_Ubicación;
    private javax.swing.JLabel Política_recuperación;
    private javax.swing.JLabel Política_reemplazo;
    private javax.swing.JRadioButton RB_Bajo_Demanda;
    private javax.swing.JRadioButton RB_Bajo_Demanda_L;
    private javax.swing.JRadioButton RB_FIFO;
    private javax.swing.JRadioButton RB_Fijo;
    private javax.swing.JRadioButton RB_Global;
    private javax.swing.JRadioButton RB_LRU;
    private javax.swing.JRadioButton RB_Limpieza_adelantada;
    private javax.swing.JRadioButton RB_Local;
    private javax.swing.JRadioButton RB_Optimo;
    private javax.swing.JRadioButton RB_Paginación_Adelantada;
    private javax.swing.JRadioButton RB_Primer_Ajuste;
    private javax.swing.JRadioButton RB_Reloj;
    private javax.swing.JRadioButton RB_Siguiente_Ajuste;
    private javax.swing.JRadioButton RB_Variable;
    private javax.swing.JButton Salir;
    private javax.swing.JLabel Tamaño_Conjunto_residente;
    private javax.swing.JLabel Tamaño_pagina;
    private javax.swing.JTextField Text_Cantidad_memoria_fisica;
    private javax.swing.JTextField Text_Cantidad_referencias;
    private javax.swing.JTextField Text_Grado_Multiprogramación;
    private javax.swing.JTextField Text_Tamaño_direcciones;
    private javax.swing.JTextField Text_tamaño_pagina;
    private javax.swing.JLabel Visualizar_estado;
    private javax.swing.JLabel bits;
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
